TAP-FrontEnd/src/pages/Main/Art/Art.jsx
TAP-FrontEnd/src/pages/Main/Art/Art.module.css
TAP-FrontEnd/src/pages/Main/Caroucel/Caroucel.jsx
TAP-FrontEnd/src/pages/Main/Header/Header.jsx
TAP-FrontEnd/src/pages/Main/Main.jsx

카드형 Caroucel 컴포넌트 생성

---

TAP-FrontEnd/src/components/Header/Header.module.css
TAP-FrontEnd/src/pages/Main/Header/Header.jsx
TAP-FrontEnd/src/pages/Main/Header/Header.module.css
TAP-FrontEnd/src/pages/Main/Home/Home.jsx
TAP-FrontEnd/src/pages/Main/Home/Home.module.css
TAP-FrontEnd/src/pages/Main/Main.jsx
TAP-FrontEnd/src/pages/Main/Main.module.css

main 틀 잡았어욤~!

---

TAP-FrontEnd/src/components/Caroucel/Caroucel.jsx
TAP-FrontEnd/src/components/Caroucel/Caroucel.module.css
TAP-FrontEnd/src/pages/Main/Art/Art.jsx
TAP-FrontEnd/src/pages/Main/Art/Art.module.css
TAP-FrontEnd/src/pages/Main/Art/Detail/Detail.jsx
TAP-FrontEnd/src/pages/Main/Art/Detail/Detail.module.css
TAP-FrontEnd/src/pages/Main/Art/List/List.jsx
TAP-FrontEnd/src/pages/Main/Art/List/List.module.css
TAP-FrontEnd/src/pages/Main/Main.jsx

공연 세부 페이지 생성

---

TAP-BackEnd/src/main/java/com/tap/files/controller/FilesController.java
TAP-BackEnd/src/main/java/com/tap/files/dao/FilesDAO.java
TAP-BackEnd/src/main/java/com/tap/files/dto/FilesDTO.java
TAP-BackEnd/src/main/java/com/tap/files/service/FilesService.java
TAP-BackEnd/src/main/resources/application.properties

files 패키지 추가

---

TAP-BackEnd/src/main/java/com/tap/z_config/GCSConfig.java

gcs config 주석 제거

---

TAP-FrontEnd/src/pages/Main/Header/Header.module.css
TAP-FrontEnd/src/pages/Main/Home/Home.jsx
TAP-FrontEnd/src/pages/Main/Home/Home.module.css
TAP-FrontEnd/src/pages/Main/Main.jsx

header 수정, 메인 수정중

---

TAP-BackEnd/src/main/java/com/tap/admin/controller/AdminBizMemberController.java
TAP-BackEnd/src/main/java/com/tap/admin/dao/AdminBizMemberDAO.java
TAP-BackEnd/src/main/java/com/tap/admin/dao/BizMemDAO.java
TAP-BackEnd/src/main/java/com/tap/admin/services/AdminBizMemberService.java
TAP-BackEnd/src/main/java/com/tap/admin/services/BizMemService.java
TAP-BackEnd/src/main/java/com/tap/biz/controller/BizApplyController.java
TAP-BackEnd/src/main/java/com/tap/biz/dto/BizApplyDTO.java
TAP-BackEnd/src/main/resources/mappers/adminbizmem-mapper.xml
TAP-FrontEnd/src/App.js
TAP-FrontEnd/src/components/Header/AdminHeader.jsx
TAP-FrontEnd/src/components/MyEditor/MyEditor.jsx
TAP-FrontEnd/src/components/MyEditor/MyEditor.module.css
TAP-FrontEnd/src/pages/ABusiness/BizContent.jsx
TAP-FrontEnd/src/pages/ABusiness/EventApply/EventApply.jsx
TAP-FrontEnd/src/pages/ABusiness/EventApply/EventApply.module.css
TAP-FrontEnd/src/pages/ASideMenu/AdminSideMenu.jsx
TAP-FrontEnd/src/pages/ASideMenu/AdminSideMenu.module.css
TAP-FrontEnd/src/pages/ASideMenu/BizSideMenu.module.css
TAP-FrontEnd/src/pages/Admin/Admin.jsx
TAP-FrontEnd/src/pages/Admin/Admin.module.css
TAP-FrontEnd/src/pages/Admin/AdminContent.jsx
TAP-FrontEnd/src/pages/Admin/AdminContent.module.css
TAP-FrontEnd/src/pages/Admin/Dash/Dash.jsx
TAP-FrontEnd/src/pages/Admin/Members/BizMem/BizMem.jsx
TAP-FrontEnd/src/pages/Admin/Members/BizMem/BizMem.module.css
TAP-FrontEnd/src/pages/Admin/Members/Members.jsx
TAP-FrontEnd/src/pages/Admin/Members/UserMem/UserMem.jsx

파일명 오타나서 지연이한테 이전에 썼던 module.css 내용 받아서 새로 생성함.

에디터 모듈.css 새로 생성

---

TAP-FrontEnd/src/components/Footer/Footer.jsx
TAP-FrontEnd/src/components/Footer/Footer.module.css
TAP-FrontEnd/src/pages/Main/Home/Home.jsx
TAP-FrontEnd/src/pages/Main/Home/Home.module.css

footer , 메인 ui 진행중

---

TAP-FrontEnd/src/pages/Main/Art/Detail/Casting/Casting.jsx
TAP-FrontEnd/src/pages/Main/Art/Detail/Casting/Casting.module.css
TAP-FrontEnd/src/pages/Main/Art/Detail/Detail.jsx

뮤지컬/콘서트 디테일 페이지 - 캐스팅 UI 구현

---

TAP-FrontEnd/src/App.js
TAP-FrontEnd/src/components/Header/Header.jsx
TAP-FrontEnd/src/pages/Login/Login.jsx
TAP-FrontEnd/src/pages/Login/Login.module.css
TAP-FrontEnd/src/pages/Sign/Member/Member.jsx
TAP-FrontEnd/src/pages/Sign/Member/Member.module.css
TAP-FrontEnd/src/pages/Sign/Sign.jsx

회원가입 ui 시작

---

TAP-FrontEnd/src/components/BookModal/BookModal.jsx
TAP-FrontEnd/src/components/BookModal/BookModal.module.css
TAP-FrontEnd/src/components/BookModal/PreventMacro/PreventMacro.jsx
TAP-FrontEnd/src/components/BookModal/PreventMacro/PreventMacro.module.css
TAP-FrontEnd/src/components/Calender/Calender.css
TAP-FrontEnd/src/components/Calender/Calender.module.css
TAP-FrontEnd/src/pages/Main/Art/Detail/Detail.jsx
TAP-FrontEnd/src/pages/Main/Art/Detail/Detail.module.css

예매 시 매크로 방지 문자 모달 창 생성 및 기능 구현 완료

예매 시 매크로 방지 문자 모달 창 생성 및 기능 구현 완료

---

TAP-BackEnd/src/main/java/com/tap/members/controller/MembersController.java
TAP-BackEnd/src/main/java/com/tap/members/dao/MembersDAO.java
TAP-BackEnd/src/main/java/com/tap/members/service/MembersService.java
TAP-BackEnd/src/main/resources/mappers/members-mapper.xml
TAP-FrontEnd/src/pages/Sign/Member/Member.jsx

아이디 중복체크 완료

---

TAP-BackEnd/src/main/java/com/tap/members/controller/MembersController.java
TAP-BackEnd/src/main/java/com/tap/members/dao/MembersDAO.java
TAP-BackEnd/src/main/java/com/tap/members/service/MembersService.java
TAP-BackEnd/src/main/java/com/tap/z_config/SecurityConfig.java
TAP-BackEnd/src/main/resources/mappers/members-mapper.xml
TAP-FrontEnd/src/pages/Sign/Member/Member.jsx

회원가입 이메일 중복체크 완료

---

TAP-BackEnd/pom.xml
TAP-BackEnd/src/main/resources/application.properties
TAP-FrontEnd/src/pages/Sign/Company/Company.jsx
TAP-FrontEnd/src/pages/Sign/Company/Company.module.css
TAP-FrontEnd/src/pages/Sign/Member/Member.jsx
TAP-FrontEnd/src/pages/Sign/Sign.jsx
TAP-FrontEnd/src/pages/Sign/Sign.module.css

회원가입 사업자 ui

---

TAP-BackEnd/src/main/java/com/tap/biz/controller/BizDesUploadController.java
TAP-BackEnd/src/main/java/com/tap/biz/controller/BizDescriptionFileController.java
TAP-BackEnd/src/main/java/com/tap/biz/controller/BizManageController.java
TAP-BackEnd/src/main/java/com/tap/biz/dao/BizDAO.java
TAP-BackEnd/src/main/java/com/tap/biz/dao/BizManageDAO.java
TAP-BackEnd/src/main/java/com/tap/biz/services/BizManageService.java
TAP-BackEnd/src/main/resources/mappers/bizmanage-mapper.xml
TAP-FrontEnd/src/components/MyEditor/MyEditorOnlyAdmin.jsx
TAP-FrontEnd/src/components/MyEditor/MyEditorOnlyText.jsx
TAP-FrontEnd/src/components/Pagination/Pagination.jsx
TAP-FrontEnd/src/components/Pagination/Pagination.module.css
TAP-FrontEnd/src/pages/ABusiness/BizManage/BizManage.jsx
TAP-FrontEnd/src/pages/ABusiness/BizManage/BizManage.module.css
TAP-FrontEnd/src/pages/ABusiness/BizManage/CurrentEvent/CurrentEvent.jsx
TAP-FrontEnd/src/pages/ABusiness/BizManage/CurrentEvent/CurrentEvent.module.css
TAP-FrontEnd/src/pages/ABusiness/BizManage/FutureEvent/FutureEvent.jsx
TAP-FrontEnd/src/pages/ABusiness/BizManage/PastEvent/PastEvent.jsx
TAP-FrontEnd/src/pages/ABusiness/EventApply/EventApply.jsx

사업자 상품관리 -관련 컴포넌트 3개 
페이지네이션 라이브러리 컴포넌트 생성

사업자 상품관리 표, Pagination컴포넌트 생성(react-pagination)

---

TAP-FrontEnd/src/components/BookModal/BookModal.jsx
TAP-FrontEnd/src/components/BookModal/BookModal.module.css
TAP-FrontEnd/src/components/BookModal/PreventMacro/PreventMacro.module.css

예매페이지 좌석 생성 구현

---

TAP-FrontEnd/src/pages/Sign/Company/Company.module.css
TAP-FrontEnd/src/pages/Sign/Member/Member.module.css

radio 클래스명 변경

---

TAP-FrontEnd/src/pages/Login/FindPw/FindPw.jsx
TAP-FrontEnd/src/pages/Login/FindPw/FindPw.module.css

비밀번호 찾기 ui

---

TAP-FrontEnd/src/components/Header/Header.jsx
TAP-FrontEnd/src/components/Header/Header.module.css
TAP-FrontEnd/src/pages/Main/Home/Home.jsx
TAP-FrontEnd/src/pages/Main/Home/Home.module.css
TAP-FrontEnd/src/pages/Main/Home/Slide/Slide.jsx

main, header css 수정

---

TAP-FrontEnd/src/components/Header/Header.jsx
TAP-FrontEnd/src/components/Header/Header.module.css
TAP-FrontEnd/src/pages/Main/Header/Header.jsx
TAP-FrontEnd/src/pages/Main/Header/Header.module.css
TAP-FrontEnd/src/pages/Main/Home/Home.jsx
TAP-FrontEnd/src/pages/Main/Home/Home.module.css
TAP-FrontEnd/src/pages/Main/Main.jsx
TAP-FrontEnd/src/pages/Main/Main.module.css

main, 헤더 수정

---

TAP-FrontEnd/src/components/Header/Header.module.css
TAP-FrontEnd/src/pages/Sign/Member/Member.jsx
TAP-FrontEnd/src/pages/Sign/Member/Member.module.css

일반회원가입 정규식 추가

---

TAP-BackEnd/src/main/java/com/tap/order/controller/OrderController.java
TAP-BackEnd/src/main/java/com/tap/order/dao/OrderDAO.java
TAP-BackEnd/src/main/java/com/tap/order/dto/PlaceAndSectionDTO.java
TAP-BackEnd/src/main/java/com/tap/order/dto/SeatsDTO.java
TAP-BackEnd/src/main/java/com/tap/order/dto/SectionInnerDataDTO.java
TAP-BackEnd/src/main/java/com/tap/order/service/OrderService.java
TAP-BackEnd/src/main/resources/mappers/detail-mapper.xml
TAP-BackEnd/src/main/resources/mappers/order-mapper.xml
TAP-FrontEnd/src/components/BookModal/BookModal.jsx
TAP-FrontEnd/src/components/BookModal/BookModal.module.css
TAP-FrontEnd/src/components/BookModal/PreventMacro/PreventMacro.module.css
TAP-FrontEnd/src/components/Calender/Calender.css
TAP-FrontEnd/src/components/PriceModal/PriceModal.jsx
TAP-FrontEnd/src/pages/Main/Art/Detail/Detail.jsx
TAP-FrontEnd/src/pages/Main/Art/Detail/Detail.module.css
TAP-FrontEnd/src/store/store.js

좌석 등급 및 티켓 날짜 출력

---

TAP-BackEnd/src/main/java/com/tap/z_config/SecurityConfig.java
TAP-FrontEnd/src/pages/Sign/Company/Company.jsx
TAP-FrontEnd/src/pages/Sign/Company/Company.module.css
TAP-FrontEnd/src/pages/Sign/Member/Member.jsx

사업자 회원가입 기능 구현, 시큐리티 추가

---

TAP-BackEnd/src/main/java/com/tap/order/controller/OrderController.java
TAP-BackEnd/src/main/java/com/tap/order/dao/OrderDAO.java
TAP-BackEnd/src/main/java/com/tap/order/service/OrderService.java
TAP-BackEnd/src/main/resources/mappers/order-mapper.xml
TAP-FrontEnd/src/components/BookModal/BookModal.jsx
TAP-FrontEnd/src/components/PriceModal/Discount/Discount.jsx
TAP-FrontEnd/src/components/PriceModal/PriceModal.jsx
TAP-FrontEnd/src/components/PriceModal/PriceModal.module.css
TAP-FrontEnd/src/pages/Main/Art/Detail/Detail.jsx
TAP-FrontEnd/src/store/store.js

* 상세 페이지에서 선택한 데이터 받아오기
* 선택한 정보 store에 저장시키기 (상품정보, 좌석, 섹션정보, 날짜, 요일)

좌석 예약페이지 수정

---

TAP-BackEnd/src/main/java/com/tap/company/controller/CompanyController.java
TAP-BackEnd/src/main/resources/mappers/members-mapper.xml
TAP-FrontEnd/src/pages/Sign/Company/Company.jsx

사업자 회원가입 사업체이름 정규표현식 수정

---

TAP-BackEnd/src/main/java/com/tap/company/controller/CompanyController.java
TAP-BackEnd/src/main/java/com/tap/company/dao/CompanyDAO.java
TAP-BackEnd/src/main/java/com/tap/company/service/CompanyService.java
TAP-BackEnd/src/main/java/com/tap/z_config/SecurityConfig.java
TAP-BackEnd/src/main/resources/mappers/company-mapper.xml
TAP-FrontEnd/src/pages/Sign/Company/Company.jsx
TAP-FrontEnd/src/pages/Sign/Company/Company.module.css

사업자 회원가입 업데이트

---

TAP-BackEnd/src/main/java/com/tap/biz/controller/BizDesUploadController.java
TAP-BackEnd/src/main/java/com/tap/members/controller/MembersController.java
TAP-BackEnd/src/main/java/com/tap/members/dao/MembersDAO.java
TAP-BackEnd/src/main/java/com/tap/members/service/MembersService.java
TAP-BackEnd/src/main/java/com/tap/z_config/SecurityConfig.java
TAP-BackEnd/src/main/resources/mappers/members-mapper.xml
TAP-FrontEnd/src/pages/Login/FindPw/ChangePw.jsx
TAP-FrontEnd/src/pages/Login/FindPw/FindPw.jsx
TAP-FrontEnd/src/pages/Login/FindPw/FindPw.module.css
TAP-FrontEnd/src/pages/Login/Login.jsx
TAP-FrontEnd/src/pages/Login/Login.module.css

비밀번호 찾기 구현 

---

TAP-BackEnd/src/main/java/com/tap/order/controller/OrderController.java
TAP-BackEnd/src/main/java/com/tap/order/dao/OrderDAO.java
TAP-BackEnd/src/main/java/com/tap/order/dto/BookDTO.java
TAP-BackEnd/src/main/java/com/tap/order/dto/OrdersDTO.java
TAP-BackEnd/src/main/java/com/tap/order/service/OrderService.java
TAP-BackEnd/src/main/resources/mappers/order-mapper.xml
TAP-FrontEnd/src/components/BookModal/BookModal.jsx
TAP-FrontEnd/src/components/PriceModal/Cancle/Cancle.jsx
TAP-FrontEnd/src/components/PriceModal/Cancle/Cancle.module.css
TAP-FrontEnd/src/components/PriceModal/Discount/Discount.jsx
TAP-FrontEnd/src/components/PriceModal/Discount/Discount.module.css
TAP-FrontEnd/src/components/PriceModal/OrderCheck/OrderChec.module.css
TAP-FrontEnd/src/components/PriceModal/OrderCheck/OrderCheck.jsx
TAP-FrontEnd/src/components/PriceModal/OrderCheck/Place/Place.jsx
TAP-FrontEnd/src/components/PriceModal/OrderCheck/Place/Place.module.css
TAP-FrontEnd/src/components/PriceModal/OrderCheck/Post/Post.jsx
TAP-FrontEnd/src/components/PriceModal/Pay/Pay.jsx
TAP-FrontEnd/src/components/PriceModal/Pay/Pay.module.css
TAP-FrontEnd/src/components/PriceModal/PriceModal.jsx
TAP-FrontEnd/src/pages/Main/Art/Art.jsx
TAP-FrontEnd/src/pages/Main/Art/Detail/Casting/Casting.jsx
TAP-FrontEnd/src/pages/Main/Art/Detail/Detail.jsx
TAP-FrontEnd/src/store/store.js

포인터 결제 예매 기능 구현

---

TAP-BackEnd/src/main/java/com/tap/detail/controller/DetailController.java
TAP-BackEnd/src/main/java/com/tap/detail/dao/DetailDAO.java
TAP-BackEnd/src/main/java/com/tap/detail/dto/DetailDTO.java
TAP-BackEnd/src/main/java/com/tap/detail/dto/ReviewStarDTO.java
TAP-BackEnd/src/main/java/com/tap/detail/service/DetailService.java
TAP-BackEnd/src/main/java/com/tap/order/controller/OrderController.java
TAP-BackEnd/src/main/java/com/tap/order/dao/OrderDAO.java
TAP-BackEnd/src/main/java/com/tap/order/service/OrderService.java
TAP-BackEnd/src/main/resources/mappers/detail-mapper.xml
TAP-BackEnd/src/main/resources/mappers/order-mapper.xml
TAP-FrontEnd/src/pages/Main/Art/Detail/Detail.jsx
TAP-FrontEnd/src/pages/Main/Art/Detail/Detail.module.css
TAP-FrontEnd/src/pages/Main/Art/Detail/Notice/Notice.jsx
TAP-FrontEnd/src/pages/Main/Art/Detail/Write/Write.jsx
TAP-FrontEnd/src/pages/Main/Art/Detail/Write/Write.module.css

기대평, 후기 입력 기능 구현

---

TAP-BackEnd/src/main/java/com/tap/coupon/dto/CouponTypeGradeDTO.java
TAP-BackEnd/src/main/java/com/tap/detail/controller/DetailController.java
TAP-BackEnd/src/main/java/com/tap/detail/dao/DetailDAO.java
TAP-BackEnd/src/main/java/com/tap/detail/service/DetailService.java
TAP-BackEnd/src/main/resources/mappers/detail-mapper.xml
TAP-FrontEnd/src/components/BookModal/BookModal.jsx
TAP-FrontEnd/src/components/Calender/Calender.css
TAP-FrontEnd/src/pages/Main/Art/Detail/Detail.jsx
TAP-FrontEnd/src/pages/Main/Art/Detail/Write/Write.jsx
TAP-FrontEnd/src/pages/Main/Home/Home.jsx
TAP-FrontEnd/src/pages/Main/Home/Slide/Slide.jsx

작품 좋아요, 댓글 공감 기능 구현

---

TAP-BackEnd/src/main/java/com/tap/order/controller/OrderController.java
TAP-BackEnd/src/main/java/com/tap/order/dao/OrderDAO.java
TAP-BackEnd/src/main/java/com/tap/order/service/OrderService.java
TAP-BackEnd/src/main/resources/mappers/order-mapper.xml
TAP-FrontEnd/src/components/Caroucel/Caroucel.jsx
TAP-FrontEnd/src/components/PriceModal/Discount/Discount.jsx
TAP-FrontEnd/src/components/PriceModal/PriceModal.jsx
TAP-FrontEnd/src/pages/Main/Art/Art.jsx
TAP-FrontEnd/src/pages/Main/Art/List/List.jsx

결재 시 쿠폰 사용 기능 추가
